.\"     Title: VIKING
.\"    Author: Ralf Meyer
.\" Generator: DocBook XSL Stylesheets v1.71.0 <http://docbook.sf.net/>
.\"      Date: 2007.05.24
.\"    Manual: 
.\"    Source: 
.\"
.TH "VIKING" "1" "2007\-05\-24" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
viking\-remote \- program to manage GPS data
.SH "SYNOPSIS"
.HP 14
\fBviking\-remote\fR
.SH "DESCRIPTION"
.PP
Viking is a free/open source program to manage GPS data. You can import and plot tracks and waypoints, show Google maps and/or Terraserver maps under it, add coordinate lines, make new tracks and waypoints, hide different things, etc. It is written in C with the GTK+ 2 toolkit, available for Linux, other POSIX operating systems, and Windows, and is licensed under the GNU GPL. If you're having a hard time visualizing it, check out the screenshots, then download and try it and tell what you think of it on the mailing list.
.PP
Homepage: http://viking.sf.net
.PP
This manual page was written for the
Debian(TM)
distribution because the original program does not have a manual page.
.PP
\fBviking\-remote\fR
is a program to manage GPS data
.SH "OPTIONS"
.PP
Usage: viking\-remote uri
.SH "SEE ALSO"
.PP
viking (1).
.SH "AUTHOR"
.PP
This manual page was written by Ralf Meyer
<ranfyy@gmail.com>
for the
Debian(TM)
system (but may be used by others). Permission is granted to copy, distribute and/or modify this document under the terms of the
GNU
General Public License, Version 2 any later version published by the Free Software Foundation.
.PP
On Debian systems, the complete text of the GNU General Public License can be found in /usr/share/common\-licenses/GPL.
.SH "AUTHOR"
.PP
\fBRalf Meyer\fR
.sp -1n
.IP "" 3n
Author.
.SH "COPYRIGHT"
Copyright \(co 2007 Ralf Meyer
.br

