Document: viking
Title: Debian viking Manual
Author: <insert document author here>
Abstract: This manual describes what viking is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/viking/viking.sgml.gz

Format: postscript
Files: /usr/share/doc/viking/viking.ps.gz

Format: text
Files: /usr/share/doc/viking/viking.text.gz

Format: HTML
Index: /usr/share/doc/viking/html/index.html
Files: /usr/share/doc/viking/html/*.html

  
