call make background.c
call make clipboard.c
call make coords.c
call make dialog.c
call make expedia.c
call make file.c
call make googlemaps.c
call make gpsmapper.c
call make gpspoint.c
call make gtkcellrendererprogress.c
call make gtkcolorbutton.c
call make http.c
call make main.c
call make mapcache.c
call make terraserver.c
call make thumbnails.c
call make vikaggregatelayer.c
call make vikcoord.c
call make vikcoordlayer.c
call make vikfileentry.c
call make vikgeoreflayer.c
call make viklayer.c
call make viklayerspanel.c
call make vikmapslayer.c
call make vikradiogroup.c
call make vikstatus.c
call make viktrack.c
call make viktreeview.c
call make viktrwlayer.c
call make viktrwlayer_propwin.c
call make viktrwlayer_tpwin.c
call make vikviewport.c
call make vikwaypoint.c
call make vikwindow.c
