name: Makefile CI

on:
  push:
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: gtk-doc-tools docbook-xsl yelp-tools libpng-dev libgtk-3-dev libicu-dev libjson-glib-dev intltool xxd
        version: 1.0
      
    - name: Prepare
      run: ./autogen.sh
      
    - name: Configure
      run: ./configure

    - name: Build
      run: make

    - name: Run check
      run: make check

    - name: Run distcheck
      run: make distcheck
